<?php

namespace tests;

use PHPUnit\Framework\TestCase as BaseTestCase;


class TestCase extends BaseTestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub


        $dotenv = \Dotenv\Dotenv::create(__DIR__,'../.env');
        $dotenv->load();
    }
}