#TODO Criar forma de receber varios arquivos de rotas
routes:
  api:
    \users:
      action: Users
      graphql: Users
      methods:
        GET: index
        POST: store
    \users\<int:id>:
      action: Users
      methods:
        GET: get_user
        PUT': update
    \users\<int:id>\create\<string:name>:
      action: Users
      methods:
        GET: get_user
        PUT': update
    \tasks:
      action: Tasks
      methods:
        GET: index
        POST: create
    \tasks\create:
      action: Tasks
      methods:
        POST: create
    \cloud:
      action: CloudServices
      methods:
        GET: index