
action_providers:
  entities: 'AnthraxisBR\FastWork\providers\EntitiesProvider'
  graphql: 'AnthraxisBR\FastWork\providers\GraphQLProvider'
  request: 'AnthraxisBR\FastWork\providers\RequestProvider'
  tasks: 'AnthraxisBR\FastWork\providers\TasksProvider'
  cloud_services: 'AnthraxisBR\FastWork\providers\CloudServicesProvider'
#fixed_providers:
    #auth:
    #  provider: AnthraxisBR\FastWork\providers\AuthProvider
    #  routes: [Users]
