
action_providers:
  entities: 'AnthraxisBR\SwooleFW\providers\EntitiesProvider'
  graphql: 'AnthraxisBR\SwooleFW\providers\GraphQLProvider'
  request: 'AnthraxisBR\SwooleFW\providers\RequestProvider'
  tasks: 'AnthraxisBR\SwooleFW\providers\TasksProvider'
  cloud_services: 'AnthraxisBR\SwooleFW\providers\CloudServicesProvider'
fixed_providers:
    auth:
      provider: AnthraxisBR\SwooleFW\providers\AuthProvider
      routes: [Users]
