
routes:
  prefix: 'api'
  api:
    users:
      action: Users
      methods:
        GET: index
        POST: store
      graphql: Users
      subroutes:
          <int:id>:
            action: Users
            methods:
              GET: get_user
              PUT': update


