server:
  http:
    host: 127.0.0.1
    port: 8101
    config:
      ssl_cert_file: null
      ssl_key_file: null
      open_http2_protocol: false
      upload_tmp_dir: null #'/data/uploadfiles/'
      http_parse_post: null
      document_root: null #'/data/webroot/example.com'
      enable_static_handler: true
      log_file: null #'/data/log/swoole.log'
      timeout: 2.5
      poll_thread_num: 2
      max_conn: 10000

worker:
  worker_num: 1
  task_worker_num: 4
  task_ipc_mode: 3
  message_queue_key: null #0x70001001
  task_tmpdir: null #/data/task/
  #websocket:
  #  host: 127.0.0.1
  #  port: 9502

  #tcp_server:
  #  host: 127.0.0.1
  #  port: 9503

  #tcp_client:
  #  host: 127.0.0.1
  #  port: 9501

  #redis:
  #  host: 127.0.0.1
  #  port: 6379

  #tasks:
  #  host: 127.0.0.1
  #  port: 9502
  #  worker:
  #    num: 4
