server:
  #http:
  #  host: 127.0.0.1
  #  port: 80

  swoole:
    host: 127.0.0.1
    port: 8103
    config:
      ssl_cert_file: '/etc/ssl/certs/swoole-selfsigned.crt'
      ssl_key_file: '/etc/ssl/private/swoole-selfsigned.key'
  #    ssl_ciphers: null
  #    ssl_method: null,
  #    open_http2_protocol: false
  #    open_http_protocol: true
  #    max_request: 10
  #    upload_tmp_dir: null #'/data/uploadfiles/'
  #    http_parse_post: null
  #    document_root: null #'/data/webroot/example.com'
  #    enable_static_handler: true
  #    log_file: null #'/data/log/swoole.log'
  #    log_level: 1
  #    timeout: 2.5
  #    poll_thread_num: 4
  #    max_conn: 10000
  #    buffer_output_size: 32 * 1024 * 1024 # byte in unit
  #    chroot: null #'/data/server/'
  #    cpu_affinity_ignore: null #[0,1]
  #    daemonize: 0
  #    discard_timeout_request: false #true
  #    dispatch_mode: null # 1 or 2 or 3
  #    dispatch_func: null #'my_dispatch_function'
  #    enable_delay_receive: true #false
  #    enable_reuse_port: false #true
  #    enable_unsafe_event: false #true
  #    group: null #'www-data'
  #    user: null # 'apache'
  #    heartbeat_check_interval: null #60
  #    heartbeat_idle_time: null #600
  #    open_length_check: null #true or false
  #    package_max_length: 81920
  #    package_length_type: 'N'
  #    package_length_offset: 8
  #    package_body_offset: 16
  #    open_mqtt_protocol: null # true or false
  #    open_tcp_nodelay: false #true
  #    open_websocket_protocol: false # true
  #    package_eof: null
  #    package_length_func: null #function closure
  #    pid_file: null #'server.pid'
  #    pipe_buffer_size: null # 32 * 1024 * 1024
  #     reactor_num: null
 #     socket_buffer_size: null # 128*1024 * 1024





worker:
  #dispatch_mode: 3
  worker_num: 1
  task_worker_num: 4
  task_ipc_mode: 3
  message_queue_key: null #0x70001001
  #task_tmpdir: null #/data/task/
  #open_cpu_affinity: null
  #open_eof_check
  #open_eof_split
  #websocket:
  #  host: 127.0.0.1
  #  port: 9502

  #tcp_server:
  #  host: 127.0.0.1
  #  port: 9503

  #tcp_client:
  #  host: 127.0.0.1
  #  port: 9501

  #redis:
  #  host: 127.0.0.1
  #  port: 6379

  #tasks:
  #  host: 127.0.0.1
  #  port: 9502
  #  worker:
  #    num: 4
