<?php


namespace tests\src\routes;

use AnthraxisBR\FastWork\Database\Migrations;
use Utils\Entities\Users;
use tests\TestCase;

class MigrationsTest extends TestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testCreateTable()
    {
        $migrations = new Migrations();

        $users = new Users();

        $migrations->createFromEntity($users);
    }
}